server:
  port: 8080
  servlet:
    context-path: /

graphql:
  servlet:
    mapping: /graphql
    exception-handlers-enabled: true
  spqr:
    gui:
      enabled: true
    relay:
      connection-check-relaxed: true